server:
  port: 8050

spring.web.resources.static-locations:
    # - classpath:/dist
    - file:./src/main/resources/dist

tensor-analyzor:
  # set to "http://127.0.0.1:5173" or "*" in dev mode
  allow-cors: null
  fields-file: fields-sample.json
  back-point: http://10.0.11.50:8060