# Java CI with Gradle

name: Java CI with Gradle

on:
  pull_request:
  push:
    branches:
      - main

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
    
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: 'gradle'

            - name: Set up nodejs 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: npm
                  cache-dependency-path: ./src/main/resources/static/package-lock.json

            - run: npm install && npm run build
              working-directory: ./src/main/resources/static
        
            - name: Build with Gradle
              run: gradle build -x npmBuild
